name: 🚀 Build, Release & Deploy
on:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  release-up:
    runs-on: ubuntu-20.04
    outputs:
      released: ${{ steps.releaser.outputs.released }}
      tag: ${{ steps.releaser.outputs.tag }}
      version: ${{ steps.releaser.outputs.version }}
      release_notes: ${{ steps.releaser.outputs.release_notes }}
      artifacts-key: 'release-artifacts'
    steps:
      - uses: actions/checkout@v2
      - uses: chaospad/releaser@v1
        id: releaser
        with:
          bump-files: |
            packages/**/package.json
            package.json
          output-file: docs/CHANGELOG.md

  build:
    if: needs.release-up.outputs.released
    needs: release-up
    uses: ./.github/workflows/re-build.yml
    with:
      artifacts-key: ${{ needs.release-up.outputs.artifacts-key }}
      tag_name: ${{ needs.release-up.outputs.tag }}

  gh-release:
    needs: [build, release-up]
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
        with:
          name: ${{ needs.release-up.outputs.artifacts-key }}
          path: dist
      - uses: softprops/action-gh-release@v1
        with:
          name: 'ngaox ${{ needs.release-up.outputs.tag }}'
          tag_name: ${{ needs.release-up.outputs.tag }}
          body: ${{ needs.release-up.outputs.release_notes }}
          files: |
            dist/artifacts/*
  deploy:
    needs: [build, release-up]
    uses: ./.github/workflows/re-deploy.yml
    with:
      artifacts-key: ${{ needs.release-up.outputs.artifacts-key }}
    secrets:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      token: ${{ secrets.GITHUB_TOKEN }}
      FIREBASE_SERVICE_ACCOUNT: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_NGAOX_LAB }}
